# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcffe1a42a22df84c94d5507a78c5dfbb0f73de5ba6153b9e83a66be62e8b50eaa2959009de1ffe24de7dccf290a32bc45470ddf47968101436bf37b37fb8c3a

test:
  secret_key_base: 1b75d7a98e0ad8338d8cd22a2c6da18db9582ceea7721f3e9fe5e24f022328e0b8cdb9e10c772a7346c578e43ce9e378698a40c24579b5e1492a75788addb14c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
